parameters:
    synolia.oroneo.form.type.import.class:                    Synolia\Bundle\OroneoBundle\Form\Type\ImportType
    synolia.oroneo.form.type.mapping.config.class:            Synolia\Bundle\OroneoBundle\Form\Type\MappingConfigType
    synolia.oroneo.form.type.mapping.config.collection.class: Synolia\Bundle\OroneoBundle\Form\Type\MappingConfigTypeCollection
    synolia.oroneo.form.type.mapping.class:                   Synolia\Bundle\OroneoBundle\Form\Type\MappingType
    synolia.oroneo.form.type.localization.config.class:       Synolia\Bundle\OroneoBundle\Form\Type\LocalizationMappingConfigType
    synolia.oroneo.form.type.localization.class:              Synolia\Bundle\OroneoBundle\Form\Type\LocalizationMappingType
    synolia.oroneo.form.type.mapping.master_category.class:   Synolia\Bundle\OroneoBundle\Form\Type\MasterCategoryType

    oro.category.class:                                       Oro\Bundle\CatalogBundle\Entity\Category
    oro.field_config_model.class:                             Oro\Bundle\EntityConfigBundle\Entity\FieldConfigModel
    oro.abstract_enum_value.class:                            Oro\Bundle\EntityExtendBundle\Entity\AbstractEnumValue
    oro.family.class:                                         Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeFamily
    oro.attribute_group.class:                                Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeGroup
    oro.product.class:                                        Oro\Bundle\ProductBundle\Entity\Product

    synolia.oroneo.form.category_mapping.name:                'synolia_oroneo_category_mapping'
    synolia.oroneo.form.attribute_mapping.name:               'synolia_oroneo_attribute_mapping'
    synolia.oroneo.form.option_mapping.name:                  'synolia_oroneo_option_mapping'
    synolia.oroneo.form.family_mapping.name:                  'synolia_oroneo_family_mapping'
    synolia.oroneo.form.attribute_group_mapping.name:         'synolia_oroneo_attribute_group_mapping'
    synolia.oroneo.form.product_mapping.name:                 'synolia_oroneo_product_mapping'
    synolia.oroneo.form.localization_mapping.name:            'synolia_oroneo_localization_mapping'

    synolia.oroneo.form.category_mapping.type:                '%synolia.oroneo.form.category_mapping.name%_type'
    synolia.oroneo.form.attribute_mapping.type:               '%synolia.oroneo.form.attribute_mapping.name%_type'
    synolia.oroneo.form.option_mapping.type:                  '%synolia.oroneo.form.option_mapping.name%_type'
    synolia.oroneo.form.family_mapping.type:                  '%synolia.oroneo.form.family_mapping.name%_type'
    synolia.oroneo.form.attribute_group_mapping.type:         '%synolia.oroneo.form.attribute_group_mapping.name%_type'
    synolia.oroneo.form.product_mapping.type:                 '%synolia.oroneo.form.product_mapping.name%_type'
    synolia.oroneo.form.localization_mapping.type:            '%synolia.oroneo.form.localization_mapping.name%_type'

services:
    # UI import form
    synolia.oroneo.form.type.import:
        class: '%synolia.oroneo.form.type.import.class%'
        arguments: ['@oro_importexport.processor.registry']
        tags:
            - { name: form.type, alias: synolia_oroneo_import_form }

    # Mapping
    synolia.oroneo.form.type.mapping.config:
        class: '%synolia.oroneo.form.type.mapping.config.class%'
        tags:
            - { name: form.type, alias: synolia_oroneo_mapping_config }

    synolia.oroneo.form.type.mapping.collection:
        class: '%synolia.oroneo.form.type.mapping.config.collection.class%'
        tags:
            - { name: form.type, alias: synolia_oroneo_mapping_config_collection }

    synolia.oroneo.form.type.mapping:
        class: '%synolia.oroneo.form.type.mapping.class%'
        arguments:
            - '@synolia.oroneo.oro_field_select'
        tags:
            - { name: form.type, alias: synolia_oroneo_mapping }

    synolia.oroneo.form.type.config.mapping.category:
        parent: synolia.oroneo.form.type.mapping.collection
        calls:
            - [setName, ['%synolia.oroneo.form.category_mapping.name%']]
            - [setType, ['%synolia.oroneo.form.category_mapping.type%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_category_mapping }

    synolia.oroneo.form.type.config.mapping.family:
        parent: synolia.oroneo.form.type.mapping.collection
        calls:
            - [setName, ['%synolia.oroneo.form.family_mapping.name%']]
            - [setType, ['%synolia.oroneo.form.family_mapping.type%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_family_mapping }

    synolia.oroneo.form.type.config.mapping.attribute_group:
        parent: synolia.oroneo.form.type.mapping.collection
        calls:
            - [setName, ['%synolia.oroneo.form.attribute_group_mapping.name%']]
            - [setType, ['%synolia.oroneo.form.attribute_group_mapping.type%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_attribute_group_mapping }

    synolia.oroneo.form.type.config.mapping.product:
        parent: synolia.oroneo.form.type.mapping.collection
        calls:
            - [setName, ['%synolia.oroneo.form.product_mapping.name%']]
            - [setType, ['%synolia.oroneo.form.product_mapping.type%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_product_mapping }

    synolia.oroneo.form.type.config.mapping.attribute:
        parent: synolia.oroneo.form.type.mapping.collection
        calls:
            - [setName, ['%synolia.oroneo.form.attribute_mapping.name%']]
            - [setType, ['%synolia.oroneo.form.attribute_mapping.type%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_attribute_mapping }

    synolia.oroneo.form.type.config.mapping.option:
        parent: synolia.oroneo.form.type.mapping.collection
        calls:
            - [setName, ['%synolia.oroneo.form.option_mapping.name%']]
            - [setType, ['%synolia.oroneo.form.option_mapping.type%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_option_mapping }

    synolia.oroneo.form.type.config.mapping.localization:
        class: '%synolia.oroneo.form.type.localization.config.class%'
        tags:
            - { name: form.type, alias: synolia_oroneo_localization_mapping }

    # Types
    synolia.oroneo.form.type.mapping.category:
        parent: synolia.oroneo.form.type.mapping
        calls:
            - [setName, ['%synolia.oroneo.form.category_mapping.type%']]
            - [setClassName, ['%oro.category.class%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_category_mapping_type }

    synolia.oroneo.form.type.mapping.family:
        parent: synolia.oroneo.form.type.mapping
        calls:
            - [setName, ['%synolia.oroneo.form.family_mapping.type%']]
            - [setClassName, ['%oro.family.class%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_family_mapping_type }

    synolia.oroneo.form.type.mapping.attribute_group:
        parent: synolia.oroneo.form.type.mapping
        calls:
            - [setName, ['%synolia.oroneo.form.attribute_group_mapping.type%']]
            - [setClassName, ['%oro.attribute_group.class%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_attribute_group_mapping_type }

    synolia.oroneo.form.type.mapping.product:
        parent: synolia.oroneo.form.type.mapping
        calls:
            - [setName, ['%synolia.oroneo.form.product_mapping.type%']]
            - [setClassName, ['%oro.product.class%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_product_mapping_type }

    synolia.oroneo.form.type.mapping.attribute:
        parent: synolia.oroneo.form.type.mapping
        calls:
            - [setName, ['%synolia.oroneo.form.attribute_mapping.type%']]
            - [setClassName, ['%oro.field_config_model.class%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_attribute_mapping_type }

    synolia.oroneo.form.type.mapping.option:
        parent: synolia.oroneo.form.type.mapping
        calls:
            - [setName, ['%synolia.oroneo.form.option_mapping.type%']]
            - [setClassName, ['%oro.abstract_enum_value.class%']]
        tags:
            - { name: form.type, alias: synolia_oroneo_option_mapping_type }

    synolia.oroneo.form.type.mapping.localization:
        class: '%synolia.oroneo.form.type.localization.class%'
        arguments:
            - '@synolia.oroneo.oro_field_select'
        tags:
            - { name: form.type, alias: synolia_oroneo_localization_mapping_type }

    synolia.oroneo.form.type.mapping.master_category:
        class: '%synolia.oroneo.form.type.mapping.master_category.class%'
        arguments:
            - '@synolia.oroneo.oro_field_select'
        tags:
            - { name: form.type, alias: synolia_oroneo_master_category_type }
