parameters:
#TODO : refactor : some parameters for entities are doubled in form_types.yml
    oro.abstract_enum_value:                                  Oro\Bundle\EntityExtendBundle\Entity\AbstractEnumValue
    oro_entity_config.attribute.entity.family.class:          Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeFamily
    oro_entity_config.attribute.entity.attribute_group.class: Oro\Bundle\EntityConfigBundle\Attribute\Entity\AttributeGroup
    synolia.oroneo.import.reader.zip.class:                   Synolia\Bundle\OroneoBundle\ImportExport\Reader\ZipFileReader
    synolia.oroneo.import.reader.attribute_group.class:       Synolia\Bundle\OroneoBundle\ImportExport\Reader\AttributeGroupReader
    synolia.oroneo.import.serializer.option.class:            Synolia\Bundle\OroneoBundle\ImportExport\Serializer\OptionSerializer
    synolia.oroneo.import.data_converter.entity.class:        Synolia\Bundle\OroneoBundle\ImportExport\DataConverter\EntityDataConverter
    synolia.oroneo.import.data_converter.attribute.class:     Synolia\Bundle\OroneoBundle\ImportExport\DataConverter\AttributeDataConverter
    synolia.oroneo.import.data_converter.option.class:        Synolia\Bundle\OroneoBundle\ImportExport\DataConverter\OptionDataConverter
    synolia.oroneo.import.data_converter.product.class:       Synolia\Bundle\OroneoBundle\ImportExport\DataConverter\ProductDataConverter
    synolia.oroneo.import.strategy.category.class:            Synolia\Bundle\OroneoBundle\ImportExport\Strategy\CategoryStrategy
    synolia.oroneo.import.strategy.attribute.class:           Synolia\Bundle\OroneoBundle\ImportExport\Strategy\AttributeStrategy
    synolia.oroneo.import.strategy.option.class:              Synolia\Bundle\OroneoBundle\ImportExport\Strategy\OptionStrategy
    synolia.oroneo.import.strategy.family.class:              Synolia\Bundle\OroneoBundle\ImportExport\Strategy\FamilyStrategy
    synolia.oroneo.import.strategy.attribute_group.class:     Synolia\Bundle\OroneoBundle\ImportExport\Strategy\AttributeGroupStrategy
    synolia.oroneo.import.strategy.product.class:             Synolia\Bundle\OroneoBundle\ImportExport\Strategy\ProductStrategy
    synolia.oroneo.import.strategy.product_file.class:        Synolia\Bundle\OroneoBundle\ImportExport\Strategy\ProductFileStrategy
    synolia.oroneo.import.writer.attribute.class:             Synolia\Bundle\OroneoBundle\ImportExport\Writer\AttributeWriter


    synolia.oroneo.import.step.schema_update.class:           Synolia\Bundle\OroneoBundle\ImportExport\Step\SchemaUpdateStep
    synolia.oroneo.import.step_element.schema_updater.class:  Synolia\Bundle\OroneoBundle\ImportExport\Item\SchemaUpdater


services:
    synolia.oroneo.import.step_element.schema_updater:
        class: '%synolia.oroneo.import.step_element.schema_updater.class%'
        calls:
            - [setEntityProcessor, ['@oro_entity_extend.extend.entity_processor']]
            - [setEntityFieldManager, ['@oro_entity_config.config_manager']]
            - [setMaintenanceMode, ['@oro_platform.maintenance']]

    # Reader
    synolia.oroneo.import.reader.zip:
        class: '%synolia.oroneo.import.reader.zip.class%'
        arguments:
            - '@oro_importexport.context_registry'

    # Serializer
    synolia.oroneo.import.serializer.option:
        class: '%synolia.oroneo.import.serializer.option.class%'
        parent: oro_importexport.serializer
        arguments:
            - '@oro_entity_config.config_manager'

    # DataConverter
    synolia.oroneo.import.data_converter.category:
        class: '%synolia.oroneo.import.data_converter.entity.class%'
        parent: oro_locale.importexport.data_converter.localized_fallback_value_aware
        calls:
            - [setMappingManager, ['@synolia.oroneo.mapping.manager.category']]

    synolia.oroneo.import.data_converter.attribute:
        class: '%synolia.oroneo.import.data_converter.attribute.class%'
        parent: oro_entity_config.importexport.data_converter.entity_field
        arguments:
            - '@oro_entity_config.config_manager'
            - '%synolia.oroneo.attribute_types_mapping%'
        calls:
            - [setMappingManager, ['@synolia.oroneo.mapping.manager.attribute']]

    synolia.oroneo.import.data_converter.option:
        class: '%synolia.oroneo.import.data_converter.option.class%'
        calls:
            - [setMappingManager, ['@synolia.oroneo.mapping.manager.option']]

    synolia.oroneo.import.data_converter.family:
        class: '%synolia.oroneo.import.data_converter.entity.class%'
        parent: oro_locale.importexport.data_converter.localized_fallback_value_aware
        calls:
            - [setMappingManager, ['@synolia.oroneo.mapping.manager.family']]

    synolia.oroneo.import.data_converter.attribute_group:
        class: '%synolia.oroneo.import.data_converter.entity.class%'
        parent: oro_locale.importexport.data_converter.localized_fallback_value_aware
        calls:
            - [setMappingManager, ['@synolia.oroneo.mapping.manager.attribute_group']]

    synolia.oroneo.import.data_converter.product:
        class: '%synolia.oroneo.import.data_converter.product.class%'
        parent: oro_product.importexport.data_converter.product
        calls:
            - [setMappingManager, ['@synolia.oroneo.mapping.manager.product']]
            - [setConfigManager, ['@oro_entity_config.config_manager']]
            - [setGlobalConfigManager, ['@oro_config.global']]

    # Strategy
    synolia.oroneo.import.strategy.category:
        class: '%synolia.oroneo.import.strategy.category.class%'
        parent: oro_locale.importexport.strategy.localized_fallback_value_aware
        calls:
            - [setCategoryRepository, ['@synolia_oroneo.category.repository']]
            - [setGlobalConfigManager, ['@oro_config.global']]

    synolia.oroneo.import.strategy.attribute:
        class: '%synolia.oroneo.import.strategy.attribute.class%'
        parent: oro_entity_config.importexport.strategy.entity_field.add_or_replace
        calls:
            - [setValidator, ['@validator']]
            - [setMappingManager, ['@synolia.oroneo.mapping.manager.attribute']]
            - [setProductMappingManager, ['@synolia.oroneo.mapping.manager.product']]
            - [setLocalizationRepository, ['@oro_locale.repository.localization']]

    synolia.oroneo.import.strategy.option:
        class: '%synolia.oroneo.import.strategy.option.class%'
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setMappingManager, ['@synolia.oroneo.mapping.manager.option']]
            - [setLocalizationRepository, ['@oro_locale.repository.localization']]

    synolia.oroneo.import.strategy.family:
        class: '%synolia.oroneo.import.strategy.family.class%'
        parent: oro_locale.importexport.strategy.localized_fallback_value_aware
        calls:
            - [setProductMappingManager, ['@synolia.oroneo.mapping.manager.product']]
            - [setEntityClass, ['%oro_product.entity.product.class%']]
            - [setDoctrineHelper, ['@oro_entity.doctrine_helper']]
            - [setConfigManager, ['@oro_config.global']]
            - [setImageGroup, ['images']]

    synolia.oroneo.import.strategy.attribute_group:
        class: '%synolia.oroneo.import.strategy.attribute_group.class%'
        parent: oro_locale.importexport.strategy.localized_fallback_value_aware
        calls:
            - [setClassName, ['%oro_entity_config.attribute.entity.attribute_group.class%']]

    synolia.oroneo.import.strategy.product:
        class: '%synolia.oroneo.import.strategy.product.class%'
        parent: oro_product.importexport.strategy.product
        calls:
            - [setConfigManager, ['@oro_entity_config.config_manager']]
            - [setDoctrineHelper, ['@oro_entity.doctrine_helper']]
            - [setLogger, ['@logger']]

    synolia.oroneo.import.strategy.product_file:
        class: '%synolia.oroneo.import.strategy.product_file.class%'
        parent: synolia.oroneo.import.strategy.product
        calls:
            - [setGlobalConfigManager, ['@oro_config.global']]
            - [setAttachmentProvider, ['@oro_attachment.provider.attachment']]
            - [setFileManager, ['@oro_attachment.file_manager']]
            - [addImageType, ['main']]
            - [addImageType, ['listing']]
            - [addImageType, ['additional', true]]

    # Processor
    synolia.oroneo.import.processor.category:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@synolia.oroneo.import.data_converter.category']]
            - [setStrategy, ['@synolia.oroneo.import.strategy.category']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%oro_catalog.entity.category.class%', alias: synolia.oroneo.import.processor.category}
            - { name: oro_importexport.processor, type: import_validation, entity: '%oro_catalog.entity.category.class%', alias: synolia.oroneo.import.processor.category }

    synolia.oroneo.import.processor.attribute:
        parent: oro_entity_config.importexport.processor.import.entity_field
        calls:
            - [setDataConverter, ['@synolia.oroneo.import.data_converter.attribute']]
            - [setStrategy, ['@synolia.oroneo.import.strategy.attribute']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%oro_entity_config.entity.entity_field.class%', alias: synolia.oroneo.import.processor.attribute}
            - { name: oro_importexport.processor, type: import_validation, entity: '%oro_entity_config.entity.entity_field.class%', alias: synolia.oroneo.import.processor.attribute }

    synolia.oroneo.import.processor.option:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setSerializer, ['@synolia.oroneo.import.serializer.option']]
            - [setDataConverter, ['@synolia.oroneo.import.data_converter.option']]
            - [setStrategy, ['@synolia.oroneo.import.strategy.option']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%oro.abstract_enum_value%', alias: synolia.oroneo.import.processor.option}
            - { name: oro_importexport.processor, type: import_validation, entity: '%oro.abstract_enum_value%', alias: synolia.oroneo.import.processor.option }

    synolia.oroneo.import.processor.family:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@synolia.oroneo.import.data_converter.family']]
            - [setStrategy, ['@synolia.oroneo.import.strategy.family']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%oro_entity_config.attribute.entity.family.class%', alias: synolia.oroneo.import.processor.family }
            - { name: oro_importexport.processor, type: import_validation, entity: '%oro_entity_config.attribute.entity.family.class%', alias: synolia.oroneo.import.processor.family }

    synolia.oroneo.import.processor.attribute_group:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@synolia.oroneo.import.data_converter.attribute_group']]
            - [setStrategy, ['@synolia.oroneo.import.strategy.attribute_group']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%oro_entity_config.attribute.entity.attribute_group.class%', alias: synolia.oroneo.import.processor.attribute_group }
            - { name: oro_importexport.processor, type: import_validation, entity: '%oro_entity_config.attribute.entity.attribute_group.class%', alias: synolia.oroneo.import.processor.attribute_group }

    synolia.oroneo.import.processor.product:
        parent: oro_product.importexport.processor.import.product
        calls:
            - [setSerializer, ['@synolia.oroneo.import.serializer.option']]
            - [setDataConverter, ['@synolia.oroneo.import.data_converter.product']]
            - [setStrategy, ['@synolia.oroneo.import.strategy.product']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%oro_product.entity.product.class%', alias: synolia.oroneo.import.processor.product }
            - { name: oro_importexport.processor, type: import_validation, entity: '%oro_product.entity.product.class%', alias: synolia.oroneo.import.processor.product }

    synolia.oroneo.import.processor.product_file:
        parent: oro_product.importexport.processor.import.product
        calls:
            - [setDataConverter, ['@synolia.oroneo.import.data_converter.product']]
            - [setStrategy, ['@synolia.oroneo.import.strategy.product_file']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: '%oro_product.entity.product.class%', alias: synolia.oroneo.import.processor.product_file }
            - { name: oro_importexport.processor, type: import_validation, entity: '%oro_product.entity.product.class%', alias: synolia.oroneo.import.processor.product_file }

    # Writer
    synolia.oroneo.import.writer.attribute:
        class: '%synolia.oroneo.import.writer.attribute.class%'
        parent: oro_entity_config.importexport.writer.entity_field
        calls:
            - [setTranslationManager, ['@oro_translation.manager.translation']]

    # Reader
    synolia.oroneo.import.reader.attribute_group:
        class: '%synolia.oroneo.import.reader.attribute_group.class%'
        parent: oro_importexport.reader.csv
        calls:
            - [setManagerRegistry, ['@doctrine']]
            - [setClassName, ['%synolia.oro.family.class%']]
