parameters:
    synolia.oroneo.mapping.manager.class:            Synolia\Bundle\OroneoBundle\Manager\MappingManager
    synolia.oroneo.import.manager.class:             Synolia\Bundle\OroneoBundle\Manager\ImportManager
    synolia.oroneo.oro_field_select.class:           Synolia\Bundle\OroneoBundle\Manager\OroFieldSelectManager
    synolia.oroneo.distant_connection.manager.class: Synolia\Bundle\OroneoBundle\Manager\DistantConnectionManager
    synolia.oroneo.helper.ftp.class:                 Synolia\Bundle\OroneoBundle\Helper\FtpHelper
    synolia.oroneo.helper.sftp.class:                Synolia\Bundle\OroneoBundle\Helper\SftpHelper


services:
    synolia_oroneo.category.repository:
        class: Synolia\Bundle\OroneoBundle\Repository\CategoryRepository
        arguments:
            - '@oro_entity.doctrine_helper'

    synolia.oroneo.import.manager:
        class: '%synolia.oroneo.import.manager.class%'
        arguments:
            - '@translator'
            - '@oro_importexport.handler.import.http'
            - '@oro_importexport.processor.registry'
            - '@oro_config.global'
            - '@synolia.oroneo.distant_connection.manager'
            - '@oro_importexport.handler.import.cli'
            - '@oro_importexport.file.file_system_operator'

    synolia.oroneo.oro_field_select:
        class: '%synolia.oroneo.oro_field_select.class%'
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_locale.helper.localization'
            - '@oro_catalog.repository.category'
            - '@doctrine'

    synolia.oroneo.mapping.manager.category:
        class: '%synolia.oroneo.mapping.manager.class%'
        calls:
            - [setConfigManager, ['@oro_config.global']]
            - [setClassName, ['category']]

    synolia.oroneo.mapping.manager.attribute:
        class: '%synolia.oroneo.mapping.manager.class%'
        calls:
            - [setConfigManager, ['@oro_config.global']]
            - [setClassName, ['attribute']]

    synolia.oroneo.mapping.manager.option:
        class: '%synolia.oroneo.mapping.manager.class%'
        calls:
            - [setConfigManager, ['@oro_config.global']]
            - [setClassName, ['option']]

    synolia.oroneo.mapping.manager.family:
        class: '%synolia.oroneo.mapping.manager.class%'
        calls:
            - [setConfigManager, ['@oro_config.global']]
            - [setClassName, ['family']]

    synolia.oroneo.mapping.manager.attribute_group:
        class: '%synolia.oroneo.mapping.manager.class%'
        calls:
            - [setConfigManager, ['@oro_config.global']]
            - [setClassName, ['attribute_group']]

    synolia.oroneo.mapping.manager.product:
        class: '%synolia.oroneo.mapping.manager.class%'
        calls:
            - [setConfigManager, ['@oro_config.global']]
            - [setClassName, ['product']]

    synolia.oroneo.distant_connection.manager:
        class: '%synolia.oroneo.distant_connection.manager.class%'
        arguments:
            - '@synolia.oroneo.helper.ftp'
            - '@synolia.oroneo.helper.sftp'

    # Helpers.
    synolia.oroneo.helper.ftp:
        class: '%synolia.oroneo.helper.ftp.class%'

    synolia.oroneo.helper.sftp:
        class: '%synolia.oroneo.helper.sftp.class%'

    # Listeners.
    synolia.oroneo.event_listener.system_config:
        class: 'Synolia\Bundle\OroneoBundle\EventListener\SystemConfigListener'
        arguments:
            - "@doctrine"
            - '%oro_user.entity.class%'
            - '%oro_organization.organization.entity.class%'
        tags:
            - { name: kernel.event_listener, event: oro_config.settings_form_preset, method: onFormPreSetData }
            - { name: kernel.event_listener, event: oro_config.settings_before_save, method: onSettingsSaveBefore }
