system_configuration:
    groups:
        oroneo:
            title: 'synolia.oroneo.label'
            icon: fa-exchange
        oroneo_global_config:
            title: 'synolia.oroneo.configuration_page.global_configuration.title'
        oroneo_mapping_config:
            title: 'synolia.oroneo.configuration_page.mapping.title'
        oroneo_global_config_settings:
            title: 'synolia.oroneo.configuration_page.global_configuration.settings'
        oroneo_global_config_localization:
            title: 'synolia.oroneo.configuration_page.global_configuration.localization.title'
        oroneo_mapping_settings:
            title: 'synolia.oroneo.configuration_page.mapping.settings'
        oroneo_config_category:
            title: 'synolia.oroneo.configuration_page.category.title'
        oroneo_config_attribute:
            title: 'synolia.oroneo.configuration_page.attribute.title'
        oroneo_config_option:
            title: 'synolia.oroneo.configuration_page.option.title'
        oroneo_config_family:
            title: 'synolia.oroneo.configuration_page.family.title'
        oroneo_config_attribute_group:
            title: 'synolia.oroneo.configuration_page.attribute_group.title'
        oroneo_config_product:
            title: 'synolia.oroneo.configuration_page.product.title'
        oroneo_config_category_settings:
            title: 'synolia.oroneo.configuration_page.category.settings'
        oroneo_config_attribute_settings:
            title: 'synolia.oroneo.configuration_page.attribute.settings'
        oroneo_config_option_settings:
            title: 'synolia.oroneo.configuration_page.option.settings'
        oroneo_config_family_settings:
            title: 'synolia.oroneo.configuration_page.family.settings'
        oroneo_config_attribute_group_settings:
            title: 'synolia.oroneo.configuration_page.attribute_group.settings'
        oroneo_config_product_settings:
            title: 'synolia.oroneo.configuration_page.product.settings'
        oroneo_config_distant:
            title: 'synolia.oroneo.configuration_page.distant.title'
        oroneo_config_distant_filepath:
            title: 'synolia.oroneo.configuration_page.distant.filepath.title'

    fields:
        # Global Configuration fields
        synolia_oroneo.default_owner:
            data_type: string
            type: oro_user_select
            options:
                label:   'synolia.oroneo.configuration_page.global_configuration.fields.default_owner.label'
                tooltip: 'synolia.oroneo.configuration_page.global_configuration.fields.default_owner.tooltip'
        synolia_oroneo.default_organization:
            data_type: string
            type: oro_organization_select
            options:
                label:   'synolia.oroneo.configuration_page.global_configuration.fields.default_organization.label'
                tooltip: 'synolia.oroneo.configuration_page.global_configuration.fields.default_organization.tooltip'
        synolia_oroneo.default_business_unit:
            data_type: string
            type: oro_business_unit_select
            options:
                label:   'synolia.oroneo.configuration_page.global_configuration.fields.default_business_unit.label'
                tooltip: 'synolia.oroneo.configuration_page.global_configuration.fields.default_business_unit.tooltip'
        synolia_oroneo.delimiter:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.delimiter'
        synolia_oroneo.enclosure:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.enclosure'
        synolia_oroneo.localization_mapping:
            data_type: array
            type: synolia_oroneo_localization_mapping
            options:
                label: 'synolia.oroneo.configuration_page.global_configuration.fields.localization_mapping'
                resettable: false
        # Category Mapping & root category
        synolia_oroneo.category_mapping:
            data_type: array
            type: synolia_oroneo_category_mapping
            options:
                label: 'synolia.oroneo.configuration_page.category.mapping'
                resettable: false
        synolia_oroneo.master_category:
            data_type: array
            type: synolia_oroneo_master_category_type
            options:
                label: 'synolia.oroneo.configuration_page.category.master_category.label'
                tooltip: 'synolia.oroneo.configuration_page.category.master_category.tooltip'
        # Family Mapping
        synolia_oroneo.family_mapping:
            data_type: array
            type: synolia_oroneo_family_mapping
            options:
                label: 'synolia.oroneo.configuration_page.family.mapping'
                resettable: false
        # Attribute group Mapping
        synolia_oroneo.attribute_group_mapping:
            data_type: array
            type: synolia_oroneo_attribute_group_mapping
            options:
                label: 'synolia.oroneo.configuration_page.attribute_group.mapping'
                resettable: false
        # Product Mapping & channel
        synolia_oroneo.product_mapping:
            data_type: array
            type: synolia_oroneo_product_mapping
            options:
                label: 'synolia.oroneo.configuration_page.product.mapping'
                resettable: false
        synolia_oroneo.product_channel:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.product.channel'
                resettable: false
        synolia_oroneo.product_image_main:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.product.image_main.label'
                tooltip: 'synolia.oroneo.configuration_page.product.image_main.tooltip'
                resettable: false
        synolia_oroneo.product_image_listing:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.product.image_listing.label'
                tooltip: 'synolia.oroneo.configuration_page.product.image_listing.tooltip'
                resettable: false
        synolia_oroneo.product_image_additional:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.product.image_additional.label'
                tooltip: 'synolia.oroneo.configuration_page.product.image_additional.tooltip'
                resettable: false
        synolia_oroneo.product_attachment:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.product.attachment.label'
                tooltip: 'synolia.oroneo.configuration_page.product.attachment.tooltip'
                resettable: false
        synolia_oroneo.attribute_mapping:
            data_type: array
            type: synolia_oroneo_attribute_mapping
            options:
                label: 'synolia.oroneo.configuration_page.attribute.mapping'
                resettable: false
        synolia_oroneo.option_mapping:
            data_type: array
            type: synolia_oroneo_option_mapping
            options:
                label: 'synolia.oroneo.configuration_page.option.mapping'
                resettable: false
        synolia_oroneo.distant_host:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.host.label'
        synolia_oroneo.distant_connection_type:
            data_type: string
            type: choice
            options:
                label: 'synolia.oroneo.configuration_page.distant.connection_type.label'
                constraints:
                    - NotBlank: ~
                choices:
                    FTP: 'synolia.oroneo.configuration_page.distant.connection_type.ftp'
                    SFTP: 'synolia.oroneo.configuration_page.distant.connection_type.sftp'
        synolia_oroneo.distant_username:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.username.label'
        synolia_oroneo.distant_password:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.password.label'
        synolia_oroneo.distant_port:
            data_type: integer
            type: integer
            options:
                label: 'synolia.oroneo.configuration_page.distant.port.label'
        synolia_oroneo.distant_passive:
            data_type: boolean
            type: choice
            options:
                label: 'synolia.oroneo.configuration_page.distant.passive.label'
                tooltip: 'synolia.oroneo.configuration_page.distant.passive.tooltip'
                choices:
                    false: 'synolia.oroneo.configuration_page.distant.passive.no'
                    true: 'synolia.oroneo.configuration_page.distant.passive.yes'
        synolia_oroneo.distant_filepath_category:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.filepath.category.label'
        synolia_oroneo.distant_filepath_attribute:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.filepath.attribute.label'
        synolia_oroneo.distant_filepath_option:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.filepath.option.label'
        synolia_oroneo.distant_filepath_family:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.filepath.family.label'
        synolia_oroneo.distant_filepath_attribute_group:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.filepath.attribute_group.label'
        synolia_oroneo.distant_filepath_product:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.filepath.product.label'
        synolia_oroneo.distant_filepath_product-file:
            data_type: string
            type: text
            options:
                label: 'synolia.oroneo.configuration_page.distant.filepath.product-file.label'

    tree:
        system_configuration:
            oroneo:
                children:
                    oroneo_global_config:
                        children:
                            oroneo_global_config_settings:
                                children:
                                    oroneo_global_config_settings:
                                        children:
                                            - synolia_oroneo.default_owner
                                            - synolia_oroneo.default_organization
                                            - synolia_oroneo.default_business_unit
                                            - synolia_oroneo.delimiter
                                            - synolia_oroneo.enclosure
                            oroneo_global_config_localization:
                                children:
                                    oroneo_global_config_localization:
                                        children:
                                            - synolia_oroneo.localization_mapping
                            oroneo_config_distant:
                                children:
                                    oroneo_config_distant:
                                        children:
                                            - synolia_oroneo.distant_connection_type
                                            - synolia_oroneo.distant_host
                                            - synolia_oroneo.distant_username
                                            - synolia_oroneo.distant_password
                                            - synolia_oroneo.distant_port
                                            - synolia_oroneo.distant_passive
                                    oroneo_config_distant_filepath:
                                        children:
                                            - synolia_oroneo.distant_filepath_category
                                            - synolia_oroneo.distant_filepath_attribute
                                            - synolia_oroneo.distant_filepath_option
                                            - synolia_oroneo.distant_filepath_family
                                            - synolia_oroneo.distant_filepath_attribute_group
                                            - synolia_oroneo.distant_filepath_product
                                            - synolia_oroneo.distant_filepath_product-file
                    oroneo_mapping_config:
                        children:
                            oroneo_config_category:
                                children:
                                    oroneo_config_category_settings:
                                        children:
                                            - synolia_oroneo.master_category
                                            - synolia_oroneo.category_mapping
                            oroneo_config_attribute:
                                children:
                                    oroneo_config_attribute_settings:
                                        children:
                                            - synolia_oroneo.attribute_mapping
                            oroneo_config_option:
                                children:
                                    oroneo_config_option_settings:
                                        children:
                                            - synolia_oroneo.option_mapping
                            oroneo_config_family:
                                children:
                                    oroneo_config_family_settings:
                                        children:
                                            - synolia_oroneo.family_mapping
                            oroneo_config_attribute_group:
                                children:
                                    oroneo_config_attribute_group_settings:
                                        children:
                                            - synolia_oroneo.attribute_group_mapping
                            oroneo_config_product:
                                children:
                                    oroneo_config_product_settings:
                                        children:
                                            - synolia_oroneo.product_channel
                                            - synolia_oroneo.product_image_main
                                            - synolia_oroneo.product_image_listing
                                            - synolia_oroneo.product_image_additional
                                            - synolia_oroneo.product_attachment
                                            - synolia_oroneo.product_mapping
